### ISSUE TITLE
Feature request: toggle on/off show control

### ISSUE THREAD

**Issue by codered11343** [bitfocus/companion-module-dataton-watchout#10]
A button that can toggle on and off show control in the Preferences menu.
Useful actions would be for: 
Timecode: (toggle) Control of Main Timeline
MIDI: (toggle) MIDI Show Contol, Device ID:

Unknown if possible, but very helpful in theatre when you need to disable show control to edit cues quickly during tech.

**Comment by albertorighetto** [comment]
To my knowledge it is not possible, there isn't a documented command to do this for the production (https://www.dataton.com/watchout-users-guide/appendix/c-control-protocol/list-of-commands).
The command timecodeMode only works for clusters, but then it wouldn't be very useful during tech.

**Comment by dnmeid** [comment]
This is not supported by the Watchout API.
