### ISSUE TITLE
instance(watchout): Network error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by a1whittaker** [bitfocus/companion-module-dataton-watchout#4]
I am getting the following error with the Watchout Module.

I open up Companion, and choose Local Host. (Watchout and Companion are running on the same Windows PC)

Once Companion has load and said its running i open up the GUI. I add in the Watchout Production PC IP address (instance(watchout): Network error: connect ECONNREFUSED 192.168.0.106:3040)

I tried this on onother PC on the same network as Watchout and Running Companion and I get same error.

**Comment by krocheck** [comment]
Have you gone into the WO preferences and enabled TCP/IP control for the project?

**Comment by a1whittaker** [comment]
No I didnt do that. Have turned that on. Now issue has been solved. Thanks!
