### ISSUE TITLE
Feature request : Feedback

### ISSUE THREAD

**Issue by Spartan17** [bitfocus/companion-module-dataton-watchout#5]
Hello all, 

I'd like to submit to your consideration and collaborate in any way possible to implement the following feature : 

**Aux Timeline - Instance Feedback**

It would be incredibly useful for the buttons to display visual information about which aux timeline is active. 

I believe implementation is possible via the websockets API getStatus function. 

Ex :  getStatus 1 "TaskList:mItemList:mItems:TaskFolder \"MyFolder\" :mItemList:mItems:TimelineTask \"MyTimeline\""

What do you think ? 

Thank you

**Comment by dnmeid** [comment]
Feedback for the Watchout module is very high at my priorities. I wanted to have this myself for ages but so far didn't find the time to implement it. It will be done, but I just can't promise when.

**Comment by dnmeid** [comment]
Feedback for the Watchout module is very high at my priorities. I wanted to have this myself for ages but so far didn't find the time to implement it. It will be done, but I just can't promise when.

**Comment by Spartan17** [comment]
> Feedback for the Watchout module is very high at my priorities. I wanted to have this myself for ages but so far didn't find the time to implement it. It will be done, but I just can't promise when.

I understand. I'm starting work on a high-pressure environment and having feedback from the Stream Deck would be very welcome. If there's anything i can do to help you, let me know. 

Thank you!

**Comment by TheWizz** [comment]
Yes, using the subscription method is the right way to go for real time updates. Be aware that the protocol implementation here for aux timelines inside folders is a bit wonky though, as the control of those timelines behaves as if the folders don't exist, while the subscription syntax must account for them.

**Comment by albertorighetto** [comment]
Do you know a command to retrieve foldes/tasks structure?

I can retrieve all aux timelines names with the command `getAuxTimelines\r` but I didn't found a way to get the folder structure, which is necessary to fully implement a feedback system.

**Comment by TheWizz** [comment]
I believe there is an addition to the getAuxTimelines command to fetch the entire tree, including the enclosing folder structure. Instead of "getAuxTimelines" send the query "getAuxTimelines tree". If you need further details here, I suggest you contact Dataton support since this apparently isn't in the official documentation.

**Comment by albertorighetto** [comment]
Currently i'm working on feedbacks on this fork/branch:
https://github.com/albertorighetto/companion-module-dataton-watchout/tree/feedbacks

To activate the feedbacks (and presets, variables and 2 more actions) you need to check "Use feedback" in the instance settings.
If you need to refresh the task/timeline lists (and presets) you have to manually use "Get Aux Timelines Names" action (there's also a preset under Commands).

Please note that it's still a draft which needs a lot of cleanup, but it is working also with tasks in folders.
It uses only subscriptions (not polling).

Currently i have implemented play/pause/stop feedbacks, some variables, a few presets and converted all input boxes to dropdown menus. There's also a "Toggle run" action to play/pause tasks based on their current status.

**Comment by dnmeid** [comment]
Solved in 1f13a324
