### ISSUE TITLE
The SetInput command does not accept parameters such as +1

### ISSUE THREAD

**Issue by DiegoMarchente** [bitfocus/companion-module-dataton-watchout#7]
Using the WATCHOUT SET INPUT command to increase or decrease a value of a Generic String, the VALUE accepts the negative parameters such as -1 or -0.01 while the positive parameters +1 or +0.01 are not accepted in the same box. If I put parameter 1, it rightly treats the parameter as a setting value and sets it to 1 instead of advancing it by 1 unit. To work around the problem I had to use a TCP-UDP SEND COMMAND command and write the complete string. I have not found any further solutions. 
Thanks
Diego Marchente

**Comment by josephdadams** [comment]
Fixed in v1.2.1
